// Parse raw product names text into individual names
// Read from stdin or file

const rawText = `
222 VIP PERFUM 24 G NEEDLE (STAR)
25GAR FREE CANDY
2BLINK EYE DROP
3DX BLEACH CREAM
3DX BLEACH CREAM SACHET
3DX LARGE BLEACH CREAM
40 LAC INJ
7UP 500ML
ABIDINE 500MG CAP
ACCU CHEK CELL
ACER 100MG TAB
ACEVIT SYP 120ML
ACEVIT TAB
ACNE AND SCARS CREAM
ACNEEZ CREAM
ACNES FAIRNESS FACE WASH
ACNEY FACE WASH 75ML
ACNISH BAR 85GM
ACNOL BAR 100G
ACTA WHITE FORT GEL 30G
ACTFREE TAB
ACTIFOL TAB
ACUVIT SYRUP
ACUVIT TAB
ACXNE AND SCARS
ACZON 1G IV INJ
ACZON 250 MG IM INJ
ACZON 500MG IM INJ
ACZON 500MG IV INJ
ADHASIVE TAPE 1
ADICOVIL INJ
ADRONIL 3MG/3ML INJ
ADULTS LINER XXL
ADVANCE BREAST PUMP
ADVIT DROPS
AFFIF 250MG TAB
AGILE TABLET 2MG
AGLOVIT SYP
AGLOVIT TAB
AGNESE TAB
AIR FRESHNER SPRAY IMPORTED
AL SHIFA BEAUTY CREAM
ALBINA CAKE
ALKI TAB (200.S)
ALLSPAN 200MG SUSP
ALLSPAN 400MG CAP
ALLSPAN SUSP 100MG/5ML
ALOE VERA GEL 260ML TUBE
ALOE VERA GEL 300GM JAR
ALOPIA PURGAIN
ALOPIA SLIM SMART
ALPHA CIP 500MG TAB
ALTRIS CORDIAL SYP
ALWAYS CLASSIC THICK 9-S LONG
ALWAYS SUPER PLUS MAXI THICK
ALWAYS ULTRA 8-S EXTRA LONG
ALZAPRED FORTE
AMERICAN CAPSULE
AMLOSHINE 5 MG TAB
ANAPALON 50MG TAB
ANC 1000 TAB
ANERON SYP
ANNOVIT M
ANPRIX T 20MG
AP MINI GLUCOMETER
AP STRIP
APETO 120ML SYP
API INN SYRUP
APIGAIN SYP
APIVIT SYP
APIXEC 120ML SYP
APIZYME SYP
APP FAST SYP 120ML
APPLE BLEACH CREAM
APPLE GOLD BLEACH CREAM
AQIQ BAR
AQUA CALL SACHET
AQUA D TAB
AQUAR PRO 5 ML
ARABIC BODY SPRAY
ARENA GOLD BEAUTY CREAM
ARENA GOLD FACE WASH
ARENA GOLD FACE WASH LARGE
ARENA GOLD MEN CREAM
ARENA GOLD SCRUB SOAP
ARENA GOLD SOAP
ARENA GOLD SUNBLOCK 90PSF
ARENA GOLD URGENT FACIAL SACHET
ARENA GOLD X MARK CREAM
ARM GRIP CRICHUS LOCAL(RZ)
AROVIT M TABLET 20S
ARQ E GHULAB 120ML
ARQ E GULAB SPRAY (MARHABA)
ARSOPAM 2MG TAB
ARSOZOLE CAP
ARTHIFLEX TABLET (20S)
ARTICURE INJ
ARULIX 150MG TAB
ASKAT 10MG TAB
ASPIN TAB 20MG
ASSURE MASK
ASTADOL TAB
ASTRID 150MG TAB
ASTRID 50MG TAB
ATOM STETHOSOCOPE CLASSIC 948
ATOM BP
ATOM GLUCOMETER WITHOUT STRIPS
ATOM STEHOSCOPE 942
ATOM STRIPS 25S LOOSE
ATOM STRIPS LOSE 25 S
ATOMIZER 3A ITALY
ATOPALM CREAM
AUGMENTIN 625 MG 12
AVANIC TAB
AVM FORTE SYP
AXON V163
AXON X136
AXON A155
AXON F15
AXON F18
AXON K 83
AXON K55
AXON K80
AXON K82
AXON V168
AZIDOR 250MG CAP
AZIFINE 250MG CAP
AZOMER 200MG SUSP
AZOMER 250MG CAP
AZOMER 500MG CAP
AZOTRAX 500MG TAB
AZOWIN 250MG CAP
AZVIT D TAB
AZVIT M TAB
B ACTIVE DROP 20ML
B ACTIVE SYRUP 120ML
B CRAIN SACHET
B FER SYP
B FORM DS CAP 30S
B NUTRITION 120ML SYP
B SMILE JUNIOR BRUSH
B SMILE TOOTH BRUSH
B,P CHECK
B/SHEET AAM DRAZ ALI
BABY BABA GOLD LARGE
BABY BABA GOLD MEDIUM
BABY BABA GOLD NEWBORN
BABY BABA GOLD SMALL
BABY BABA GOLD XL
BABY BABA GOLD XXL 6
BABY BABA LARGE
BABY BABA MEDIUM
BABY BABA NEWBORN
BABY BABA SMALL
BABY PRO BALM
BABY RASH CREAM
BABY WIPES SUNNYGOLD
BABYWIPES
BMW
BACK SHEET AMM CHAIR ALI
BACK SHEET LONG ANGEL CHAIR
BACTIGEN 32OMG TAB
BACTIRID DS SYP
BACTOBAN GEL
BAG
BALANCE PROBIOTIC SACHET
BANNET TOOTH PASTE 100GM
BARIRA BEAUTY CREAM
BED PAN BLUE(RZ)
BED PAN L
BED PAN SEP
BED PAN SP(RZ)
BED POT WHITE SP
BEGE FEEDER LARGE
BELADONA PLASTAR
BELINI HAIR COLOUR RED
BELINI HAIR COLOUR BLACK
BELINI HAIR COLOUR DB
BELINI HAIR COLOUR GOLDAN
BELLAKT GF 200GM
BELTAPRO CREAM
BENZI SPRAY
BENZIM NATRAL SYP 120ML
BERG SNOWFALL (L)
BERG SNOWFALL (S)
BEROCCA PERFORMANCE 15S
BEST AID PRETTY PINK (24.S)
BETABAR EYE DROPS
BETABISOL N DROP
BETAWIS G CREAM
BETAWIS S CREAM
BETOXI 20MG
BIG BODY 3 RAZER
BIN BERRY SACHET
BIO 21 CHINA
BIO 21 SANTE
BIO 21 TAB
BIO D3 INJ
BIO D3 TAB
BIO PG STRIP
BIOCID 120ML SYP
BIOCOS BEAUTY CREAM
BIOCOS CREAM F
BIOCOS FACE WASH
BIOCOS MEN CREAM
BIOCOS SERUM
BIOCOS URGENT FACIAL
BIOFAD CREAM
BIOGLIT SHAMPOO
BIOLYN ANTI HIAR FALL SHAMPOO
BIOMIL FORMULA POWDER LF 400GRM
BIOMIL LF 400GM
BIOMOUSSE FLORA 120ML
BIOPRIDE 50MG
BIOPSY JAR MEDIUM
BIOPSY JAR SMALL
BIOTIN PLUS 2500MCG TAB
BIOTIN SHAMPOO
BISCA RS 50
BISCA RS 20
BLACK BEAUTY POWDER 150 G
BLACK BLEACH CREME
BLACK COBRA TAB
BLACK MARKET PERFUM
BLACK MASK
BLACK SEED OIL 25ML
BLADE #23
BLESSO CREAM
BLEACH 50 GM
BLOOD BAG 250ML
BLOOD CULTURE BOTTEL
BLUE LADY PERFUME ORIGNAL
BONCAL D TAB
BONCOR D SUSP
BONCOR D TAB
BONTIN SYP
BONTIN TAB
BOOST SYP
BOUNTY BOWL PORT
BOXEF 500MG CAP (12.S)
BP BLADER FINE
BP CHECKUP
BP MERCURY ALPK2 JAPAN
BP MERCUY ATOM AT940
BRANULA CATH 24G
BRANULA FIXER
BRAVO TOOTH BRUSH SMOKER
BREAST CREAM JAR
BRIDO HONEY LOTION 120ML
BSR
BUBBIES DIAPER
BUILDCAL SYP
BUILDCAL TAB
BURET SET(ALSHIFA)
BUTTER SCOTCH RS 5
BUTTERFLY 140
BUTTERFLY ALL GAGE
BUTTERFLY LARGE VALUE PACK
BUTTERFLY MATERNITY PAD 6S
BUTTERFLY MAXI T5HICK MINI PINK
BUTTERFLY PAD
BUTTERFLY PADS MAXI L VALUE PACK
BUTTERFLY PADS MAXI XL VALUE PACK
BUTTERFLY SUPER PLUS MAXI THICK
BYE BYE FEVER PATCH
C-VITA CREAM 20G
CAC 1000 PLUS TAB LOOSE 20S
CACBEBE 5 JUNIOR (40) S
CACBEBE 5 JUNIOR 26S
CADIBON DROPS
CADIBON SYP
CADIBON TAB
CAJO TAB
CAKE RS 40
CAL DEE INJ
CAL OM3 TAB
CALAZI 500MG TAB
CALCEPLEX SACHET
CALCI D
CALCIJON SACHET
CALCIU FORTE TAB
CALCIVIT PLUS TAB
CALFUM D TAB
CALTIG+D3
CALTIS 125MG/5ML SYP
CALTIS 250MG/5ML SYP
CALVI D TAB
CALVIK D SYP
CALWAY 120ML SYP
CALXIGO + TAB
CAM Z SYP 120ML
CAMERA WIPES
CAMFR0Y XL 10
CAMFROY LARGE 10S
CAMFROY MEDIUM 10S
CAMFROY XL 10 S
CAMRY SCALE ELETRONIC
CANBEB EX LARGE 10S
CANBEB EX LARGE 5 S
CANBEB JUNER 8 S
CANBEB JUNERS 6 S
CANBEB MINI 54S
CANBEBE 5 6PCS
CANBEBE (4 MAXI PLUS 50 PCS)
CANBEBE (6 )10 PCS)
CANBEBE (MID 3( 36 PCS)
CANBEBE 1 NEW BORN 2-5KG 1OS
CANBEBE 1 NEW BORN 84PCS
CANBEBE 1 NEW BRON (48.S)
CANBEBE 2 3-6KG 40 S
CANBEBE 2 74 PCS
CANBEBE 3 MIDIUM 62 PCS
CANBEBE 3 MIDIUM 36 PCS
CANBEBE 4 32 S
CANBEBE 4 58PCS
CANBEBE 4 7-18KG 7S
CANBEBE 5 52PCS
CANBEBE 5 (JUNIOR 26 PCS)
CANBEBE 5 28 PCS
CANBEBE 5 JUNIOR 30
CANBEBE 6
CANBEBE 6 (24S)
CANBEBE 6 (32 PCS)
CANBEBE 6 24PCS
CANBEBE 6 46PCS
CANBEBE DIAPERS 6
CANBEBE EX TRA LARGE 5/ 8S
CANBEBE EXTRA LARGE 10 S
CANBEBE EXTRALARGE 5 S
CANBEBE JUMBO 6
CANBEBE JUNIOR 26S
CANBEBE JUNIOR 5 )40 PCS)
CANBEBE JUNIOR 5 / 8S
CANBEBE JUNIOR 6/S
CANBEBE MAXI 32 S
CANBEBE MAXI 4/ 7S
CANBEBE MIBI 46S
CANBEBE MIDI /8/ S
CANBEBE MIDI 3 /46S
CANBEBE MINI 2 /54S
CANBEBE MINI 2 14S
CANBEBE MINI2 / 9 S
CANBEBE NEW BORN 10S
CANBEBE NEW BORN 14 S
CANBEBE SUPER MAXI 32S
CANBEBE TRIAL PACKS
CANBEBE WIPES(64/PCS)
CANBEBE WIPES(88/PCS)
CANBEBE(4 )10 PCS)
CANBEBE(5) 8 PCS)
CANBEBS NEW BON 14 S
CANDI BUTTERSCOTCH
CANDIA 150MG CAP
CANDY
CANDY IMP RS 2
CANDY IMP RS 5
CANDY LOCAL
CANPED LARGE PATIENT DIAPER
CANSA 2.5MG TAB
CAPSULE SMALL
CARACORT CREAM
CARE BABY DIAPER L 80
CARE BABY DIAPER M 88
CARE BABY DIAPER NEW BORN
CARE BABY DIAPER S 96S
CARE BABY DIAPER XL
CARE FREE PADS
CARE GLOVES
CARE HEEL CREAM
CARE PRICKLY HEAT POWDER
CARESSE COOL PRICKLY POWDER 125G
CARESSE HANDWASH 250ML
CARESSE HANDWASH 500ML
CARTIFLEX CAPSULE
CARTIFLEX FORT TAB
CAST 4
CAST 5
CATACROME EYE DROP
CATGUT 1#
CATGUT 2#
CBC VAIL
CC OIL
CD SYP
CD TAB
CE REX SYP
CECOBAL INJ
CEFISCOT 100MG/5ML 60ML
CEFRADIN SYP
CELL GLUCOMETER
CELL PENCIL
CEPMOL T TAB
CEPOL T TAB
CERELAC 3 FRUITS POUCH 175GM
CERIDAL SYP
CERTEZA ANERIOD BP
CERTEZA BP 405
CERTEZA METER
CERTEZA STRIP GL 108
CERTEZA WEIGHT MACHINE
CHALID COMMOD F
CHANDNI CREAM
CHAP STICK
CHAP STICK LIP OIL
CHARGING CELL
CHARLIE PERFUME
CHATOOLI TAB
CHEROFEX 60MG TAB
CHERRY ON SYP
CHERRY ON TAB
CHERRY POLISH SMAL
CHERRY POLISH LARGE
CHEST INN SYRUP
CHESTEX COUGH SYP
CHESTIALL IV SUGER FRE SYP
CHIC BUBBLE
CHICKEE 5
CHINA 4 PAAD FOOT RABER(RZ)
CHINA CRICHUS FOOT ORIGNAL(RZ)
CHINA CRICHUS FOOT RABER(RZ)
CHINA STICK FOOT RABER(RZ)
CHINA WALKER FOOT RABER(RZ)
CHOCOLATE RS 50
CHOCOLATE RS 60(YOU)
CHOLI D CAP
CIALUS GOLD TAB
CIBCOS IVY SYP
CICLOXAL 400MG CAP
CIPRO 250MG (BRAINFLOX)
CIPRO 500MG(BRAINFLOX)
CIPRO EFF TAB 250MG
CIPROFED 250MG TAB
CIPROFED 500MG TAB
CIPROVID 500MG TAB
CIPTOP 250MG SYP
CIPTOP 250MG TAB
CIPTOP 500MG TAB
CIPVIT SYP
CITICOR SYP 500MG/5ML
CIXIM SYP
CLARISET 250MG TAB
CLEAN UP
CLEANER 500ML
CLEANC (HAND WASH)
CLEPAM 0.5MG TAB
CLIN-V CREAM 40GM
CLINDER KEY
CLINDER OXGEN 3K
CLINDER OXGEN 48
CLINDER OXGEN 5KG
CLINIC PLUS SHAMPOO
CLINICA M/W 200ML
CLOMIT CREAM
CLOTISONE H CREAM 30G
COA 100MG SYP
COA 400MG CAP
COBOR TOOTH BRUSH
COCOMO RS 70
COD MIC 3
CODIL P DROPS
CODIL P SYP
COFCOR 120ML
COFGABZ SYP 120ML
COFPEL SYP
COFTA SYP
COGESIC PLUS TAB
COKA COLA 1.5 LTR
COKA COLA 500ML
COKE O.5 L SUGAR FREE
COLAGIN SACHET
COLGATE PASTE ORIGINAL 100GM
COLGATE PASTE SENSITIVE ORIG 50 GM
COLGATE PASTE TOTAL ADVANCE 40G
COLGATE PASTE TOTAL CHARCOAL
COLGATE SENSITIVE ORIGINAL 30GM
COLGATE SENSITIVE PRO RELIEF 70GM
COLGATE SENSITIVE PRORELIEF 100GM
COLGATE SPARKLE PASTE 130 MG
COLGATE TOOTH BRUSH KIDZ
COLGATE TOOTH BRUSH PREMIER CL
COLGATE TOOTH BRUSH SLIMSOFT
COLGATE TOOTH BRUSH TWISTER
COLIC DROP GLORIOUS
COLLAMIT 20 TABLETS
COLOR MATCH SHAMPOO SACHET
COLRID DROP
COMFAM
COMFOR CREAM
COMFOR LOTION 200ML
COMFORT 120ML SOLUTION
COMFORT 355ML SOLUTION
COMFORT COLLAR HARD(M,L,XL)
COMFORT COLLAR N CUFF 1.5M
COMFORT COLLAR N CUFF 1M
COMFORT KNEE SUPPORT XXL
COMFREY (DIGNITY SHEET)
COMFREY (M MANA)
COMFREY DIAPERS XL
COMFROY MEDIUM 10S
COMMD CHAIR RED FIX
COMMOD CHAIR SILVER/FIX
COMMOD CHAIR B/KUPA ALI
COMMOD CHAIR D/P AMM ALI
COMMOD CHAIR D/P L/A ALI
COMMOD CHAIR D/P RED
COMMOD CHAIR D/P RED(RZ)
COMMOD CHAIR D/PCUPA SPECIAL
COMMOD CHAIR FIX BLUE(RZ)
COMMOD CHAIR FIX RED(RZ)
COMMOD CHAIR GRY ALI
COMMOD CHAIR JALI/W ALI
COMMOD CHAIR KY890 NOOR
COMMOD CHAIR NISA 710
COMMOD CHAIR RED ALI
COMMOD CHAIR W;;M (RZ)
COMMOD CHAIR894(NR)
COMMOD STOOL BLUE(RZ)
COMMOD STOOL FANSI ALI
COMMOD STOOL RED(RZ)
COMMODE CHAIR 815 MANA
COMMODE CHAIR 817MANA
COMMODE CHAIR 894 MANA
COMMODE CHIAR KY(890)
COMMODO CHAIR WHEEL USA
CONVIDOL CF TAB
COOL BABY
COOLING FEVER PATCH
COOL GEL SYP
COOL PATCH
COOLING GEL FEVER PATCH
COOVER 100MG SUSP 30ML
COOVER 400MG CAP
COOVER DS 200MG/5ML SUSP
CORBEE TAB
COREZCOL SYP
CORLAX SYP
COSOME LOZENGES
COTTON BANDAGE 2 INCH
COTTON BANDAGE 2.5 INCH
COTTON BANDAGE 3 INCH
COUGH BIT SYP
COVATE LOT 60ML
COVID 19 SPRAY
COVY SYP 120ML
CPAM 0.5MG TAB
CRANBEX SACHET
CRANOMED SACHET
CRANOVIT SACHET
CRUCHES CHINA(M) RZ
CRUCHES IRON(RZ)
CRUTCH KY925 USA
CRUTH HAMID
CRUTH RUBBAR
CRUTH RUBBER USA
CRUTH SAIF
CRUTH USA L
CRUTH WOOD SAIF
CUBIC TAB
CULINAX TAB
CURASPAN 200MG/5ML SUSP
CUTEXIA 400MG CAP
CYCLOGESIC TAB
D D ONE ULTRA TAB
D PLEX SYP
D PLUS 3 DROPS
D PLUS TAB
D ROSE TAB
D SHINE DROPS
D SHINE TAB 200000
D SHOT ORAL LIQ
D TREAT
D3 1ML INJ
D VITAL
D WELL INJ
D-TIME DROPS
D/P LONG ANGEL ALI
D/P LONG ANGEL DARAZ
D/S 500ML
D3 STAT CAP
DABUR AMLA HAIR OIL INDIA
DABUR AMLA HAIR OIL INDIA 90ML
DABUR RED PASTE 100 GM
DADU DIAPER L
DADU DIAPER M
DADU DIAPER(XL)
DAIRY MILK RS 20
DAIRY MILK RS 30
DAIRY MILK ALMOND RS.75
DAIRY MILK OREO RS.
DAISY PAD
DANZEN FLAT TAB
DARAZ ALI AM
DARAZ ALI FANCY
DARAZ AM ALI
DARPHIN 250MG CAP
DARPHIN 500MG CAP
DELITE AIR FRESHNER 300ML
DELITE HAND WASH
DELYCIA PERFUME LARGE
DENCARE BLEED M/W
DENCARE BLEED TOOTH PASTE
DENCARE PLUS TOOTH PASTE
DENCARE SENSITIVE M/W
DENCARE WHITE M/W
DENCARE WHITE TOOTH PASTE
DENSO BEAUTY CREAM
DENSO BEAUTY SOAP
DENTAL FLOSS T PICK
DENTO FRESH MOUTH WASH
DENTO FRESH TOOTH PASTE
DENTO MED TOOTH PASTE 70GM
DENTOLIN T
DENTONIC 50G
DEON 200000 IU TAB
DEOTRIX CREAM
DEPO QUEEN 1ML INJ
DEPSON TAB
DERMA PLUS BEAUTY CREAM
DERMAXIL FACE WASH
DERMAZON (SKIN,HAIR NAIL)
DETEFEN 120ML SUSP
DETORA 120ML SYP
DETRAN P
DETTOL SOAP 3 IN 1 95G
DETTOL SOAP 3IN 1 100GM
DETTOL SOAP 65G
DETTOL SOAP COOL 138GM
DETTOL SOAP SKIN CARE 95GM
DETTOL SURFACE CLEANER
DEU 11 CREAM
DEVIO+ DROPS
DEVIO+ TAB
DEVIT INJ
DEW DROP HEART CHOCO BALLS
DEWISS SR 100MG TAB
DEXA INJ
DEXA TAB
DEXER EYE DROP
DEXY 120ML SYP
DFENAC 75MG TAB
DIABETIC SOCKS 9-11
DIALYZER NEEDLE 16
DIALYZER NEEDLE 17G
DIAPER COMFREY EXT LARGE
DIAVUE GLUCO STRIP
DIAZEPAM INJ
DIGAS ANTACID SACHET
DIGESTIVE BISCUIT S/F
DIGITAL BP UA 651 JAPAN
DIGITAL BP WRIST LC60 USA
DIGTAIL BP UB351 JAPAN
DINOPEN INJECTION
DINOPEN INJECTION WITH LIDOCAIN
DINOPEN TABLET
DISDINE TAB 5MG
DIVOL 120ML SYP
DO CONDOM
DO IT BODY SPRAY 250ML
DO IT PERFUME
DOCTOR ANTI LICE SACHET
DOCTOR HAND SANITIZER
DOCTOR TOOTH PAST WITH 2 T/B
DOCTOR TOOTH PASTE 100GM BRUSH
DOCTOR TOOTH PASTE 220GM
DOCTOR TOOTH PASTE 22OGM W/BRUSH
DOCTOR TOOTH PASTE 70GM BRUSH
DOLBY 20MG TAB
DOLNOT PLUS INJ
DOSAVIL INJ (AVIL)
DOSCAL T TAB 20S
DOUBLE PATI AMM ALI
DOUBLE PATI LONG ANGEL ALI
DR KOFF HONEY
DR KOFF LOZENGES
DR RASHEL SUN BLOCK 170ML
DR TALBEENA CERELAC ALMOND
DR TALBEENA PISTA,KAJOO,FRUIT
DR TALBEENA SUGAR FREE 285
DR WEST TOOTH BRUSH
DULOSOFT 20MG (14S)
DUREX SENSITIVE CONDOM
DYNAM DROP 10ML
DYNAMIC ELBO
DYNAMIC KNEE ALL
DYNAMIC POLYSLING ALL
DYNAMIC WRISR
DYNAQUIN TABLET 500MG
E400 VIT E TAB
EAFA BODY SPRAY
EAR PHONE EAR SPEAKER HEARING
EAR WIRE
EASYON SPRAY
EB CHEK STRIP
EDEN AIR FRESHENER
EDEN ROCK HAIR TONIC
EDEN ROCK TALC POWDER
ELBO STICK (911) MANA
ELBO STICK NABI
ELBOW STICK 923(NR)
ELOCID SYP
EMANI 7OILS IN ONE
EMPTY CAPSULE 500 MG
EMSCAL D
ENCHANTEUR SPRAY 150ML
ENERON CELL (AA)
ENERON CELL (AAA)
ENFAMIL 4 A+ 400GM
ENFAMIL A+ PREMATURE 400MG
ENGLISH ANTI LICE SHAMPOO 200ML
ENGLISH ANTI LICE SHAMPOO 60ML
ENGLISH PRICKLY HEAT KIDS POWDER
ENGLISH TOOTH PASTE 70 GM
ENGLISH TOOTH PASTE 140GM
ENGROW SACHET
ENTROBAC SACHET
ENZI FLAM TAB
EPIAO 4000IU INJ
EPOSHE TAB
EPTI SYP
EPTIC SYP
ERIBION TAB
ERYPACK 250MG TAB
ERYPACK 500MG TAB
ES CARE 20MG CAP
ESCiwink 10MG TAB
ESOSON 40MG CAP
ESPOLE 20MG CAP
ESSOFED 20MG
ETAPRAM TAB
EU CREAM SACHET
EU HAIR REMOVE CREEM 30ML
EVERYDAY RS 15
EVOCHECK METER
EVOCHECK STRIP
EXECUTIVE TOOTHBRUSH
EXOTAN 10/160MG TAB
EXOTAN 5/160MG TAB
EXOTAN 5/80MG TAB
EYCANE EYE DROP
EYE PADS
EYEPAT EYE DROP
EZ DOSE PILL BOX
EZ KID NAPPY RASH CREAM
FA SOAP (175GM)
FABLOUS LIQUID 50ML
FABRUL TAB
FACE FRESH JAR
FACE MASK 10 IBL
FACE MASK CLOTH IMP
FACE MASK K95 ASSURE
FACE MASK PIN
FACE ONN CAPSULE
FACEMASK HOOKS
FAIR & LOVELY CREAM SACHET
FAIR & LOVELY 10RS SASHYE
FAIR & LOVELY WINTER CREAM
FAIR MENZ
FAIRNESS CREAM 35GM
FAIR WAR TAB
FAIZA BLEACH CREAM SACHET
FAIZA NEEM SOAP 100GM
FAMILIA PARTY PACK TISSUE
FASHION MASK
FAST NEBULIZER
FEBUSTAT 40MG TAB
FEEDER PURE LOVE 150ML
FELDENE DISP 10MG
FEMAX SACHETS 10
FEMINA SYP
FEMOKAST 4MG SACHET
FEPTID 40MG
FERINET CHEW TAB
FERININJECT 50MG INJ 10ML
FERPI
FERROMIT TAB
FERTI H TAB
FERULIN INJ 70/30
FEURI BEAUTY CREAM
FEURI BLEACH CREAM
FEVER SCAN STRIP
FIDASE 10MG TAB
FIGHTER LOTION SACHET
FIGHTER POWDER
FIGHTER SPRAY
FINGER WAX
FINLAC 2 400MG
FIRST READ
FIRSTSIGN PLUS 1/S
FIX CHAIR AMM KUPA
FIX CHAIR DARZ ALI
FIX CHAIR FANCY KUPA
FIXOMULL STRECH 10CM*10CM
FLAEM VICK STEAMER
FLAGYL FLAT INJ
FLAT GRIPE WATER
FLEXO GEL
FLORA SANITARY PADS 16 PCS XXL
FLUACT INSTA SACHET
FLUACT SYP
FLUMAG CAP 150 MG
FLURBY 100MG
FLUTET EYE DROP
FOFO LOTION LARGE
FOFO LOTION SMALL
FOGG BODY SPRY 120ML
FOLDING FLASH ALI
FOLY CATHER PIGEON 16&18
FOMICID 10MG CHEWABLE TAB
FORCON CAP 150MG
FORHANS PASTE 200GM
FORHANS PETROLIUM JELLY
FORMALIN 400ML
FORMULA COM/CLEAN T/B
FORMULA EXTRM/CLEAN T/B
FOUR PAD(931) MANA
FOXAMINE 200MG TAB
FRENDCOGEN 100MG TAB
FRIST AID BOX
FUDGE CANDY
FUSICARE CREAM
G CAL M TAB
G GEL SYP
G MET SUSP 120ML
G MONT SACHET
GABZ CAL3 TAB
GABZ CIDLAX 120ML
GAMMEX GLOVES
GARENT C SYP 120ML
GARENT C TAB
GARNIER SHAMPOO 2250ML
GARNIER SHAMPOO 400 ML
GASTRIL PLUS JAR PLAIN
GASTROWAY SYP
GDCID TABLET 40MG
GEN-XING CAP
GENRO
GENRO VIT CAP
GENTICYN INJ 80ML
GEO COLOUR
GESUNDEN PREVIT
GILSPAN 100MG 5ML SYP
GILSPAN 400MG CAP
GILSPAN DS 200MG 5ML SYP
GINKGO S TAB
GLADIO 10MG TAB
GLAMOUR BODY LOTION
GLOMIN BAR
GLORIOUS ISPAGHOL100GM JAR
GLOST SUPPLEMENT 200G
GLOW MAN FACE WASH
GLUCOFIT STRIPS
GLUCON D
GLUTATHION TAB
GLUTONE C CREAM 30GM
GLYCERIN 150GM CORTEX
GLYCERIN 25GM CORTEX
GLYCERIN 300GM CORTEX
GLYTIM HC
GLYZIA 50MG TAB
GLYZIA MET 50/500MG TAB
GO RASH POWDER MOTHER CARE
GODREJ COLOUR
GOLDEN PEARL HAIR COLOR
GOLDSPEC 400MG TAB
GONADOBOOST TAB
GOOD NITE PAMPER LARGE
GOOD NITE PAMPER MEDIUM
GOOD NITE PAMPER SMALL
GOOD NITE PAMPER X LARGE
GOODDAY BRUSH
GOREE WHITENING CREAM
GOREY FEEDER 60ML
GROWPHIL TAB (20.S)
GULABO MARHAM
GYTRIM HC CREAM
HAIR AND HANDSOME CREAM
HAIR BRUSH KING WOOD
HAIR BRUSH MAQ
HAIR OFF CREAM
HAIR SPRAY
HALE D PLUS TAB
HALECID 120ML SYP
HALF ROLL
HANCOBAL 500MCG INJ
HAND SANDTIZER PUMP 250ML
HANKIES GLORIA TISSUES
HANKIES HIP HOP TISSUES
HANKIES HOP UP TISSUES
HAPPIES DIAPERS ALL
HAPPYDENT GUM
HARALIN POWDER
HARICEF 400MG CAP
HARICEF SUSP
HARRIFLOX 400MG TAB
HAZEL M CREAM
HAZEL M FACE WASH
HAZMEENA CHORAN
HAZMOGIN PHAKKI 25GM
HB MALT 120ML SP
HBSAG HCV TEST
HCXONE 2G IV INJ
HEAD & SHOULDERS SHAMPO 185 ML
HEAD & SHOULDERS SHAMPOO 360ML
HEAD S SHOULDERS CONDITIONER
HEALER CAP 20MG
HEALER CAP 40MG
HEAMOCARE SYP
HEARING AID F007
HEARING AID HA93C
HEARING AID SP
HEATING PADS BE240
HEATING PADS BE220
HEDERA 4 SYP
HEEL CARE 30GM
HELLO HAIR SHAMPOO 100 ML
HEMANI COCONUT OIL 200ML
HEMANI COCONUT OIL 100ML
HEMANI COCONUT OIL 400ML
HEMANI COCONUT OIL 50ML
HEMANI FACE WASH
HEMANI HERBAL SLIM TEA
HEMANI HONEY 250GM
HEMANI WHITENING CREAM
HEP-52 DS TAB
HERBIACTIVE OINTMENT
HERBIGEL SYP
HERBION ANTILICE SHAMPOO
HERNIA BELT SMART(RZ)
HEXALOR 5MG TAB
HICROM PLUS TAB JAR (30)
HIFAZAT
HIFAZAT SANITIZER 50ML
HIFLOIC 300MCG TAB
HIGH CAL C SACHET
HILOFT 50MG TAB
HIRAZINE TABLET 10MG
HISOPT EYE DROP
HOEST LOZENGES
HOEST ACTIVE
HOEST CANDY (1 S)
HONEY 500GRM
HONEY KHALIS LARGE JAR
HONEY MINI JAR
HONEY ORIGINAL 250GM
HONEY SMALL JAR
HOP F TAB
HORLICK CHOCOLATE SACHET 18GM
HORSE POWER CREAM
HOT BOTTLE
HSS 10CC SYRING
HSS 10CC SYRING 1S
HUDA TALIA BLEACH CREAM
HUSSAIN MANJAN 25GM
HYDROPHIL 5% LOTION 180ML
HYDROSKIN PLUS CREAM
HYPATITUS B AND C
HYPOMER DROP
HYSTANE EYE DROPS
IBOPRUFEN SYP
IBTOL 100MG/5ML SYP
IMUMED PREGNANCY TEST STRIPS)
INCREEZ-D
INDAZ 250 MG CAP
INDAZ 500 MG CAP
INGLOT D SYP
INGLOT D TAB
INHALER (MEDICS)
INJ INJEKET PATIENT
INMOX TAB 400MG
INSULIN SYRING YMS
IONA INJ
IRF TAB
IRON PRO SYP
IRON PRO TAB
IRONA 120ML SYP
IRONATE TAB
IROPAS SYP
IROPAS TAB
IROVIT INJ
ISOTOP GEL
ISPAGHOL QARSHI HUSK
ISPOGEL SACHETS MINT
ISPOGEL SACHETS ORANGE
ITODIL 50MG TAB
IVTUS SYP
JAEFEN 400MG TAB
JAIT CAPSULE
JAMBOO BOTTLE
JAME SHIRIN 3LTR
JAME-SHIRIN 1500ML
JAME-SHIRIN 800ML
JARTIS D3 200000IU
JASOM SACHET
JAZZ 100
JAZZ 300
JAZZ 600
JHALAK BLACK MASK
JHALAK CREAM
JHALAK FACE WASH
JHALAK SERUM
JHALAK SOAP
JHALAK URGENT FACIAL
JMOVE
JOHAR JOSHANDA (POORA HAMDARD)
JOHNSON 300ML LOTION
JOHNSONS BABY POWDER 100G
JOHNSONS BABY POWDER 200G
JOHNSONS BABY SHAMPO 100ML
JOHNSONS SOAP 100 G
JOLEN BLEACH
JOSH CONDOM
JOSH DELAYING CONDOM (3S)
JUNSUI FACE WASH 50GM
K KOUF SYRUP
K-CA+ TAB
K-FER TAB
KAAM SYRUP
KAJU TAB
KALAKOLA HAIR COLOUR 43 LARGE
KALAKOLA HAIR COLOUR NO 41,39
KALAKOLA HAIR TONIC 100ML
KALAKOLA HAIR TONIC 200ML
KALI GLYCERIN
KALKOLA HAIR TONIC 200ML
KALSIP 120ML SYP
KALZEC C SACHET
KAM GEL
KAM LOTION
KANREACH TAB
KAOPLAST POULTICE
KARSITA 50/500MG TAB
KARSITA TAB 50/1000 MG
KENAC 75MG TAB
KESHIA OIL
KETODON CREAM 25GM
KEUNE HAIR BEAUTY CAPSULE
KEUNE HAIR COLOR 1000
KEUNE HAIR COLOUR NO. 5.67
KEUNE HAIR COLOUR NO. 8.3
KEUNE TINTA COLOR
KHERAL LARGE
KHERAL MEDIUM
KHERALSMALL
KIDCO FEEDER 250 HANDLE
KIDS TOOTHBRUSH
KIN D 200000 IU TAB
KING CAII SMALL
KING CALL BIG
KING COIL BLACKY
KINGTOX BED BUG KILLER 325ML
KINGTOX GLUE TRAP (MOUSE&RAT
KINGTOX LED SET
KINGTOX MAT
KINGTOX POWDER INSECT KILLER
KINGTOX RAT KILLER
KINGTOX REFFIL LIQUID
KINGTOX SPRAY 300ML ODOURLESS
KINGTOX SPRAY 350ML
KINGTOX SPRAY 400 ML
KLARICID XL TAB
KLARISEF 125MG SYP
KLARISEF 250MG TAB
KLARISEF 500MG TAB
KLCM FORTE SACHET
KLIMAX EXTACY PLUS 3S
KLIMAX INTENSE 3S
KLIMAX PERFORMA 3S
KLIMAX PLEASURE MIX 4S
KLIMAX PURPAL X
KLOZEPAM 2MGTAB
KN 95 3D MASK
KNEE BRACE PAIR (MANA)
KNIGHT RIDER SPRAY LARGE
KNIGHT RIDER TUBE CREAM
KOFEM PLUS SYP
KOFOUT SYP
KOHINOOR AMLA HAIR OIL
KONCEPT 20MG
KRAKE CREAM 20GM
KRIDE 40 MG TAB
KUFTROL IVY LEAF 120ML SYP
KULFA TOFFFE
KUPA ALI
KUPA DARAZ ALI
KUPA FANCY ALI
KURKURE RS 10
LABOOB E KHAS UL KHAS ASHRAF
LACTO COVER MILK 400G
LACTOBAC SACHET
LACTOLAX SYP
LADIES SACHET
LADY RAZER PINK
LAFAXINE ER 100MG TAB
LAKTY SACHET
LAM PURE POKET TISSUE
LAMCIT 250MG TAB
LAMCIT 500MG TAB
LANA BABY WIPES
LANCING DEVICE
LAP SPONGES
LARGO CREAM
LASA SYP
LATIF SURMA
LAYS 10
LAYS RS 20 ALL
LAYS RS.30 ALL
LAZMA CREAM 15GM
LE WET OINT
LEMON WAX SOFT TOUCH 125G
LENOVARIN SYP
LENSIDE EYE DROP 10ML
LEO PAMPERS SMALL
LERIDAL
LERNEX TAB
LEUCOPIN CAPSULE 1
LEUCOPIN INJECTION 4ML
LEVODOR TABLET 250MG
LEVODOR TABLET 500MG
LEXAN BAR
LIBIDO CONDOMS TIN IMP
LIBS ACTIVE PROBIOTIC
LIDOCAINE INJ
LIFE CARE DIAPPER (M)
LIFE CARE DIAPPER(L)
LIFE CARE DIAPPER(XL)
LIFE CARE DIGITAL THERMAMETER
LIFE CARE GLOVES
LIFE CARE HEARING AID 302 BLUE
LIFE CARE HEARING AID 304
LIFE CARE LC60
LIFE CARE STEMER
LIFE CARE W/S BR2017
LIFE CHEK GLUCOMETER
LIFE CURE BP METER
LIFEBUOY HAND SANITIZER LARGE
LIGCY EAR DROP
LILLY TISSUE PCKT
LILLY PERFUMED TISSUES
LIMILK
LINOPHEK
LINVESTA 5 MG TAB
LIP OIL 7ML
LIPIGON TAB
LIPTON TEA 50S BAG
LIPTON TEA BAG
LIRIL CAP
LISTRO HEAL M/W
LIVION B SYP
LIVTRA 20MG TAB
LIXA SYP
LIXA TAB
LOCAL CRICHUS FOOT RABER(RZ)
LOGIRID 250MG TAB
LOPIUM 2MG CAP
LORALION TAB
LORDIN SYP
LOREAL CONDITIONER
LORGY TAB
LOSANTA 50MG TAB
LOSANTA DIU TAB
LOUD N CLEAR NJ 7470
LOXICAM 15MG
LUBE EYE DROP
LUBREX OINTMENT 75GM
LUBRICANE EYE DROP 15ML
LUDA AIR FRESHENER
LUDE SHOE POLISH
LUMBER BACK BELT L M XL
LUMBER BACK BELT XXL
LUSAM 100MG TAB
LUSAM 50MG TAB
LUTEK SYP
LUTEK TAB
LUTEVIT ADVANCE SYP
LUTEVIT ADVANCE TAB
LUX SOAP 70G
LUZY (TAB)
LYF D CAP
LYFE FEEDER 280ML
LYFVIT TAB
MACDAFIN TABLET 50MG
MACMIN SYP
MACNAZ ORAL DROPS
MACNAZ ORAL GEL 10G
MACNAZ RASH CREAM 20GM
MACROWIN 200MG/5ML
MACROWIN 250MG CAP
MACZIN SUSP 200MG
MAJOON MUGHALIZ 60 GM
MALRICH SUPPLEMENT 200GM
MALTO MAX SACHET
MAMAMIL GOLD VANILA MILK
MANDELAC FACE WASH 100ML
MARGAL MOUTH WASH
MARK ICE COOL FACE WASH
MARQUISE BODY SPRAY 200 ML
MARVI CREAM JAR
MASFER SYP
MASK KN95 ORIGNAL
MASK N95 SIMPLE
MASTER 3CCSYRING
MAVINATE INJ
MAXALL LOTION 100ML
MAXEL CELL
MAXELL CELL (CR 2032)
MAXSUN D TAB
MAXTOX SPRAY 325ML
MAXVIT TAB
MAYO-MAX SACHET
MAZA JUICE
MCARE OINT
MECHICO BABY FEEDER MEDIUM
MECHICO BABY FEEDER SMALL
MECOGEN SL 500MCG
MECOWIN INJ
MEDICAM BLEACH LARGE
MEDICAM BLEACH SMALL 15GM
MEDICAM PRO TOOTH PASTE 70GM
MEDICAM TOOTH POASTE 25 GRAM RS 30
MEDICARE NEBULIZER
MEDICO BP55
MEDICS CHILDREN COUGH SYP
MEDISOL D/S 500ML
MEDORA POWDER (L) 275GM
MEDOXIM 100MG/5ML SYP
MEDOXIM 200MG/5ML SYP
MEDOXIM 400MG CAP
MEGA TAR
MEIJI KIDS PLUS 600GM
MEJA ALL BRACE
MELATEC PLUS CREAM
MELUKAST 10MG TAB
MENACTRA ID VIAL
MENSOFORT D SYP
MERODINE 200MG TAB
METHYLATED WATER BOTTLE 1 LITRE
METOST 10MG
MEVULAK SACHET
MEWIN TAB
MG CAL D SYP
MICRO CELL (CR 2032)
MILANO CHOCOLATE
MIRTH SHILAJIT SHOT
MISC.
MITEX LOTION
MOBICAL SACHET
MOBIROM 8MG TAB
MOFTAB 400MG TAB
MOLAM 400MG TAB
MOLFIX DIAPER 1 NB 84S
MOLFIX DIAPER 2 80S SMALL
MOLFIX DIAPER 3 MID 72PCS
MOLFIX DIAPER 4 LARGE 64PCS
MOLFIX DIAPER 5 (11-18KG) 60PCS
MOLFIX DIAPER 6 XL 52 PCS
MOLFIX NO. 2 68S
MOLFIX NO. 3 60S
MOLFIX NO. 4 54S
MOLFIX NO. 5 48S
MOLFIX NO. 6 42S
MOLFIX NO.1 78S
MONTIS PETROLEUM JELLY 50GM
MOOV K 75 GM
MORCIN 40MG
MORINAGA BF P 400GM
MORO TOFEE RS 5
MORTEIN COOPEX POWDR
MORTEIN INSTA INSECT KILLER 230ML
MORTEIN SPRAY PEACEFUL NIGHT
MOSFREE
MOSQUTE OIL
MOSPEL RAPID LAVENDER SPARY
MOSQUITO LOTION
MOSRID BAND
MOSQUITO MOTHER CARE BABY OIL 65ML
MOTHERCARE BABY POWDER 90GM
MOTHERCARE BABY SHAMPOO
MOTHERCARE LOTION 60ML
MOUTH WASH
MOXAL SYRUP 120ML
MOXIMAG
MOZOLE 20MG SACHET
MOZOLE 40MG CAP
MR WHITE TOOTH PASTE 40GRM
MT SOFT TAB
MUCORID 120ML SYP
MUFCAM 20MG
MUMSIK 90 CAP
MY BRUSH
MYCONA GB CREAM 20MG TAB
MYDAKLA TAB (28.S)
MYFOL DROPS
MYFOL SYP
N B 20MG
NABIZ 5 MG TAB
NADO @ 15
NADO CHOCOLATE
NALOREX 50MG TAB (28.S)
NAMAZ CHAIR
NANA SMARTY L 74S
NANA SMARTY M 82S
NANA SMARTY NB 50S
NANA SMARTY S 82S
NANA SMARTY SMALL 72P
NANA SMARTY XXL 6, 26S
NAPPY RASH CREAM
NAPPY RASH CREEM CARE 25ML
NAPROXEN 550MG TAB
NAPZOL 20MG CAP
NAPZOL 40MG
NATALVIT CAP
NAVIA LOTION
NAZDAC INJ
NEBULIZER NATOM (NEB919
NEBULIZER V CHECK
NECOBAL INJ
NEFRAMIN TAB
NEMSIS 100MG TAB
NEO KLAR 250MG SUSP 70ML
NEOFIT KNEE BRACE
NEOFIT SPINAL SUPPORT
NEPATEK E/D
NESCAF SCHT
NESFRUITA JUICE 1 L
NESFRUTA JUICE
NETCAL D TAB
NETTO CAP
NEUROBION FLAT INJ
NEXERA TOOTH PASTE 150GM
NEXTON BABY LOTION
NEXTON BABY RASH POWDER 50 GM
NEXTON BABY SHAMPOO
NG TUBE 10 NO
NG TUBE 8 NO
NG TUBE ALL
NICHIPORE TAPE 1" (SURGICAL)
NIFLAM M/W 200ML
NIFT 250MG TAB
NIFT 500MG TAB
NIFT SYP 250MG/5ML
NIGELLA HAND SANITIZER 60ML
NIMKO 5
NIMZZ
NIPPLE IMPORTED LARGE
NIPPLE LARGE
NISA (DISPOSABLE SYRINGE)
NISA 10CC SYRINGE
NISA PERFUMED TALC POWDER
NITO TAPE 1 INCH
NITROFURANTION 100MG
NIVEA 75ML LOTION
NIVEA LOTION DRY SKIN 125 ML
NIVEA SOFT CREAM 50ML
NIVEA SOFT JAR 50ML
NIZWA FACE WASH
NIZWA HAIR OIL
NMT TAB
NO SPA INJ FLAT
NOCOX 7.5MG TAB
NOFEA MAXI EASY
NOIR BODY SPRAY
NONCID- 20MG 14S
NORANGI UBTAN LARGE
NORANGI UBTAN SMALL
NOSTIF K TAB
NOVA PLAST
NOVATEPH 20MG CAP
NOVATEPH 40MG CAP
NOVOMIX 30 FLEXPEN 3ML.
NOVOVATE N CREAM
NOW PASTER RS 5
NSIDE 100MG TAB
NT CID 120ML SYP
NT FUNGAL 150MG CAP
NU SURE 200 GM SOFT PACK
NUCAL K TAB
NURALAC 1 400G
NURALAC 2 400G
NURALAC 3
NURALAC LF
NUTKAL TAB
NUTRAFIL 1 400GM
NUTRAFIL 2 400GM
NUTRAFIL 3 400GM
NUTRAFIL LF 400GM
OBFAM TAB
OCID SYP
OCION D TAB
OFER SYP
OILUM SOAP
OK DELAY CONDOMS
OLGA BEAUTI CREAM
OLIVE OIL AL RASHEED 400ML
OLIVE OIL ALRASHEED 175ML
OLIVIA BLEACH CREAM 30GM LARGE
OLIVIA BLEACH CREAM SMALL 40RS
OLIVIA BLEACH HALDI SMALL 50RS
OLIVIA LOTION 220ML
OLPER POWDER MILK 900GM
OLPERS 390GM
OMEFIT 20MG
OMEGA 3 SYP
OMEGA SNOW FAMILY PACK
OMNIPAQUE INJ 100ML
OMODIT POWDER
OMRON M2 BASIC METER
ONDAN SYRUP
ONDASET INJ
ONDESTERON SYP
ONE D3 SOFTGEL CAP
ONE TOUCH (CONDOM LIGHTS)
ONE TOUCH (CONDOM LONG LOVE)
ONE TOUCH SELECT (25 S)
ONEFER INJ
ONSET SYP
ONSTIL 120ML
ONVATE LOT 20ML
OPERON NEBULIZER
OPT-D SOFT GEL CAP 200000IU
OPTICLEAR E/D
OPTICON A EYE DROP
OPTIKET EYE DROP
OPTIM EYE DROP
OPTINAC EYE DROP
OPTM EYE DROP
ORA-D3 INJ
ORAL B (VISION TOOTH BRUSH)
ORAL B CLASSIC T/B
ORCY EYE DROP
ORCYDEX EYE DROP
ORL (ORS)
ORPIC 500
ORTHOFLEX FORT TAB
OSDURA SACHET
OSDURA TAB
OSI D
OSI TAB
OSPOR ORAL SUSP (8S)
OSTEO K SYP
OSTEO K TAB
OSTEOVIT TAB (20.S)
OSTEROL D TAB
OTSUKA 0.9% NACL 25 ML AMP.
OVASITOL TAB
OVER HALL
OVITAX TAB 30S
OXCYM DR 20MG CAP
OXGEN REGULATER
OXGEN STAND
PAEDI CARE LIQ ORANGE 500ML
PAINGO CREAM
PAINLESS 50MG TAB
PAINLESS 75MG TAB
PAINNIL P TAB 50MG
PAINSA INJ
PAKSOL NS 1000ML
PAKSOL NS 100ML
PAKSOL NS 500ML
PALMOLIVE SHAMPOO 180ML
PAMPER 1 NEWBORN 2-5KG (21S)
PAMPER 2 SMALL 3-8KG (10S)
PAMPER 3 MEDIUM 6-10KG (18S)
PAMPER 3 MEDIUM 6-10KG (9S)
PAMPER 4 LARG 7-18KG (8S)
PAMPER 4 LARGE
PAMPER 5 JUNIOR 11-25KG (8S)
PAMPER 6 XX LARGE
PAMPER NEWBORN BABY
PAMPER S MEDIUM 36
PAMPERS PREMIUM CARE MEGA PACK
PAMPERS SMALL 40
PANADOL FLAT
PANAGON INJ
PANOT TAB
PARADISE AIR FRESHENER 300ML
PARADONTAX COMPLETE PROTECTION
PARADONTAX EXTRA FRESH 100GM
PARADONTAX EXTRA FRESH 50GM
PARADONTAX ORIGINAL 100GM
PARADONTAX ORIGINAL 50GM
PARLEY CREAM BLEACH 40G
PARLEY FAIRNESS FACE WASH
PARLEY GOLD CREAM BLEACH
PARLEY HAIR REMOVAL SACHET
PARLEY NOMARKS CREAM
PCF TAPE
PD CEF 250MG IM INJ
PD MEEK 500MCG INJ
PDROX 500MG CAP
PEACH CREME BLEACH SOFT TOUCH
PENTAZOCINE
PERFECT NEBULIZER
PERFECT TOOTH PASTE
PERISON CR TAB
PERMETHRINE LOTION
PGB NEO 75MG CAP
PHAKI KALONGI SMALL
PHAKI LARGE
PHAKKI SMALL
PHENYL 2.75 LTR
PHILADELPHIA COLLAR
PHILIPS NEBULIZER
PHILOSOPHER OIL
PHYTO-COMPLEX TABLET (20S)
PICO NEBULIZER ITALY 3A
PIGEON BREAST
PILES EX POWDER 1GM
PILL CUTTER
PINK B BEAUTY CREAM
PINQ D SYP 120ML
PIROXIL GEL
PK CELL AA2 2S
PK CELL AA4 4S
PK CELL AAA 2S
PK CELL AAR6P 1.5V HD
PK CELL EXTRA HEAVY DUTY AA
PK CELL EXTRA HEAVY DUTY AAA
POCKET TISSUE 24S
POFERA-F TABLET
POISON POWDER
POLISH
POLYFER FA SYP 60ML
POLYSLING L
POLYTEARS EYE DROP
POLYTEK OPTHALMIC GEL
PONDS FACE WASH 100GM
PONDS FACE WASH PIMPLE CLEAR
PONDS MOISTURISING LOTION 50ML
POTASSIUM CHLORIDE AMP.
POTATO (FEEDING BOTTLE 80ML)
POTATO FEEDER 150ML W/HANDLE
POTATO FEEDER 15O ML
POTATO FEEDER 250ML
POTATO FEEDER 280ML HANDLE
POTATO TARINING CUP
POWER NEBULIZER
POWER PLUS INSECT KILLER SPRAY
POWER PLUS SPRAY 500ML
POWER TONE F138
POWER TONE F883
POWERFULL TOOTHBRUSH
PP 2 - 270ML FEEDER
PRAIMA COLOUR
PRECAL D TAB
PRECIZ (PREGNANCY TEST STRIP)
PREGNA ESENTIAL TAB
PREGNA EZ TAB
PREGNALYF TAB
PREGNANCY STRIP
PREGWELL TAB
PRICKLY HEAT POWDER 100GM
PRICKLY HEAT SOAP
PRISM 40MGCAP
PRO ACTIVE SACHET
PRO MASK 2S
PROCOLIC DROP
PRODENT MOUTH WASH 200ML
PROGACE 160MG TAB
PROGUM PASTE JUNIOR
PROGUM TOOTH PASTE
PROLAM 0.25MG
PROLAM 1MG TAB
PROLENE 3.0 R/ B/C CHINA
PROLENE 4/0
PROLENE6/0
PROMICE TAB
PROP AC 40MG CAP
PROSENSE DS
PROTECT DENT TAB
PROTECT ENAMEL
PROTECT G PLUS TOOTH PASTE
PROTECT SMILE TOOTH PASTE
PRUDENCE CONDOMS U0SA
PULCON 150MG CAP
PULDOL INJ 75MG 5S
PULVILOX 250MG TAB
PULVILOX 500MG TAB
PURE BLACK BODYSPRAY
PURE LOVE FEEDER 150ML
PURE LOVE FEEDER 280ML
PUREL FACE WASH
PURIDON 10MG
PURIN SHAMPOO 90ML
Q CAST 4
Q-MOX EYE DROP
QALSAN TABLET LOOSE
QEZAN 250MG
QLIME 100MG
QMOX TAB
QTEC CREAM
QUACKER OATS 200GM
QUACKER OATS POUCH 500GM
QUACKER OATS TIN 500GM
QUINALOX 250MG TAB
QUINALOX 500MG TAB
QZONE 250MG IV INJ
R-MAX GEL 35GM
RABEFARM 20MG TAB
RABILING INJ ANTI RAB
RABITON 20MG CAP (10.S)
RADIFLUC 150MG CAP
RAHAT ADULTS PAMPERS LARGE
RAHAT ADULTS PAMPERS MEDIUM
RAHAT ADULTS PAMPERS XL
RAHAT SOFT PACK TISSUE
RAMTIN CHOCLATE
RASAGIN 0.5MG TAB (10.S)
RAYBAN FORT LOTION
RAYBAND 10*10 /1S
RCD TAB
RECIPER 20MG CAP
RECON HAIR WAX 125ML JAR
RECON POP UP TISSUE
RECON SMART POP UP TISSUE
RED PLUS EXTRA GLOW CREAM
RED TOOTH PASTE 200GM
REDIN F TAB
REDIN M SYP
REDIN M TAB
REFINE 19 LTR WATER
REHYDRO ORS ORANGE
RELAXCIT C SYP
RELTUS C&F 100ML
RELTUS DM 120ML
RESFYL SYP
RESOURCE DIABETES
RESPIRO EBULIZER 3A ITALY
RESSASI BODY SPRAY
REVALP 500MG TAB
REVOCAL D SUSP
REVOSIT TAB
REXYL SYP
REZAL 40MG CAP
RICH D TAB
RIO GLASS FEEDER L(DR GYM)
RIO GLASS FEEDER M (DR GYM)
RIO GLASS FEEDER SMALL (DR GYM)
RIPRO+ZINC SACHET
RITHROCIN 500MG
RITHROCIN 250MG CAP
RIVAJ UK SUN BLOCK 150ML
ROCKET WIPES
ROCKY DIAPER
ROGER 75MG CAP
ROGHAN E ZAITON
ROMANCE PERFUME SPRAY
ROSE PETAL TISSU ROLL
ROSE ROSE PETAL TOILET ROLL
`;

// Clean up: split by newlines, trim, filter empty
const names = rawText
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line.length > 0);

// Deduplicate (case-insensitive)
const seen = new Set<string>();
const unique: string[] = [];
for (const name of names) {
  const lower = name.toLowerCase();
  if (!seen.has(lower)) {
    seen.add(lower);
    unique.push(name);
  }
}

console.log(`Total names: ${names.length}`);
console.log(`Unique names: ${unique.length}`);
console.log("---ARRAY_START---");
console.log(JSON.stringify(unique, null, 2));
console.log("---ARRAY_END---");
